# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.29.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.29.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dante/Desktop/reacthreejs/SCT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dante/Desktop/reacthreejs/SCT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.29.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.29.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dante/Desktop/reacthreejs/SCT/CMakeFiles /Users/dante/Desktop/reacthreejs/SCT//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dante/Desktop/reacthreejs/SCT/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sct

# Build rule for target.
sct: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sct
.PHONY : sct

# fast build rule for target.
sct/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sct.dir/build.make CMakeFiles/sct.dir/build
.PHONY : sct/fast

src/cli_parser.o: src/cli_parser.cpp.o
.PHONY : src/cli_parser.o

# target to build an object file
src/cli_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sct.dir/build.make CMakeFiles/sct.dir/src/cli_parser.cpp.o
.PHONY : src/cli_parser.cpp.o

src/cli_parser.i: src/cli_parser.cpp.i
.PHONY : src/cli_parser.i

# target to preprocess a source file
src/cli_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sct.dir/build.make CMakeFiles/sct.dir/src/cli_parser.cpp.i
.PHONY : src/cli_parser.cpp.i

src/cli_parser.s: src/cli_parser.cpp.s
.PHONY : src/cli_parser.s

# target to generate assembly for a file
src/cli_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sct.dir/build.make CMakeFiles/sct.dir/src/cli_parser.cpp.s
.PHONY : src/cli_parser.cpp.s

src/cpu_sim.o: src/cpu_sim.cpp.o
.PHONY : src/cpu_sim.o

# target to build an object file
src/cpu_sim.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sct.dir/build.make CMakeFiles/sct.dir/src/cpu_sim.cpp.o
.PHONY : src/cpu_sim.cpp.o

src/cpu_sim.i: src/cpu_sim.cpp.i
.PHONY : src/cpu_sim.i

# target to preprocess a source file
src/cpu_sim.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sct.dir/build.make CMakeFiles/sct.dir/src/cpu_sim.cpp.i
.PHONY : src/cpu_sim.cpp.i

src/cpu_sim.s: src/cpu_sim.cpp.s
.PHONY : src/cpu_sim.s

# target to generate assembly for a file
src/cpu_sim.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sct.dir/build.make CMakeFiles/sct.dir/src/cpu_sim.cpp.s
.PHONY : src/cpu_sim.cpp.s

src/file_io.o: src/file_io.cpp.o
.PHONY : src/file_io.o

# target to build an object file
src/file_io.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sct.dir/build.make CMakeFiles/sct.dir/src/file_io.cpp.o
.PHONY : src/file_io.cpp.o

src/file_io.i: src/file_io.cpp.i
.PHONY : src/file_io.i

# target to preprocess a source file
src/file_io.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sct.dir/build.make CMakeFiles/sct.dir/src/file_io.cpp.i
.PHONY : src/file_io.cpp.i

src/file_io.s: src/file_io.cpp.s
.PHONY : src/file_io.s

# target to generate assembly for a file
src/file_io.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sct.dir/build.make CMakeFiles/sct.dir/src/file_io.cpp.s
.PHONY : src/file_io.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sct.dir/build.make CMakeFiles/sct.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sct.dir/build.make CMakeFiles/sct.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sct.dir/build.make CMakeFiles/sct.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/text_proc.o: src/text_proc.cpp.o
.PHONY : src/text_proc.o

# target to build an object file
src/text_proc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sct.dir/build.make CMakeFiles/sct.dir/src/text_proc.cpp.o
.PHONY : src/text_proc.cpp.o

src/text_proc.i: src/text_proc.cpp.i
.PHONY : src/text_proc.i

# target to preprocess a source file
src/text_proc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sct.dir/build.make CMakeFiles/sct.dir/src/text_proc.cpp.i
.PHONY : src/text_proc.cpp.i

src/text_proc.s: src/text_proc.cpp.s
.PHONY : src/text_proc.s

# target to generate assembly for a file
src/text_proc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sct.dir/build.make CMakeFiles/sct.dir/src/text_proc.cpp.s
.PHONY : src/text_proc.cpp.s

src/vectorizer.o: src/vectorizer.cpp.o
.PHONY : src/vectorizer.o

# target to build an object file
src/vectorizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sct.dir/build.make CMakeFiles/sct.dir/src/vectorizer.cpp.o
.PHONY : src/vectorizer.cpp.o

src/vectorizer.i: src/vectorizer.cpp.i
.PHONY : src/vectorizer.i

# target to preprocess a source file
src/vectorizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sct.dir/build.make CMakeFiles/sct.dir/src/vectorizer.cpp.i
.PHONY : src/vectorizer.cpp.i

src/vectorizer.s: src/vectorizer.cpp.s
.PHONY : src/vectorizer.s

# target to generate assembly for a file
src/vectorizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sct.dir/build.make CMakeFiles/sct.dir/src/vectorizer.cpp.s
.PHONY : src/vectorizer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sct"
	@echo "... src/cli_parser.o"
	@echo "... src/cli_parser.i"
	@echo "... src/cli_parser.s"
	@echo "... src/cpu_sim.o"
	@echo "... src/cpu_sim.i"
	@echo "... src/cpu_sim.s"
	@echo "... src/file_io.o"
	@echo "... src/file_io.i"
	@echo "... src/file_io.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/text_proc.o"
	@echo "... src/text_proc.i"
	@echo "... src/text_proc.s"
	@echo "... src/vectorizer.o"
	@echo "... src/vectorizer.i"
	@echo "... src/vectorizer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

